uploads = []
outputs = []

[[generated]]
id = "0VprOp2LwacUiVFTtn9f6"
uri = "file://artifacts/mustasharek/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dvR4--GBOgn_aAJWX2pDl"
uri = "file://artifacts/mustasharek/assets/images/splash-icon.png"
type = "image"
title = "generated_image"
