import { Feather } from "@expo/vector-icons";
import React from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import colors from "@/constants/colors";

const C = colors.light;
export type ConsultationType = "email" | "chat" | "phone" | "video";
export function isScheduledConsultation(type: ConsultationType) { return type !== "email"; }
export function BookingTypeSelector({ value, onChange, options }: { value: ConsultationType; onChange: (v: ConsultationType) => void; options?: ConsultationType[] }) {
  const list = options ?? ["chat", "phone", "video", "email"];
  const meta: Record<ConsultationType, { label: string; icon: keyof typeof Feather.glyphMap; color: string }> = {
    email: { label: "استشارة مكتوبة (بريد إلكتروني)", icon: "mail", color: C.gold },
    chat: { label: "محادثة نصية", icon: "message-square", color: C.primary },
    phone: { label: "مكالمة هاتفية", icon: "phone", color: "#2563EB" },
    video: { label: "مكالمة فيديو", icon: "video", color: "#7C3AED" },
  };
  return <View style={styles.section}><Text style={styles.title}>نوع الاستشارة</Text><View style={styles.grid}>{list.map(type => { const m=meta[type]; const active=value===type; return <TouchableOpacity key={type} onPress={()=>onChange(type)} style={[styles.typeCard, active && {borderColor:m.color,backgroundColor:`${m.color}10`}]}><View style={[styles.icon,{backgroundColor:active?m.color:"#F4F5F7"}]}><Feather name={m.icon} size={18} color={active?"#fff":m.color}/></View><Text style={[styles.label,active&&{color:m.color}]}>{m.label}</Text></TouchableOpacity>})}</View></View>;
}
export function EmailNotice() { return <View style={styles.notice}><Feather name="mail" size={18} color={C.gold}/><Text style={styles.noticeText}>تنبيه: هذه استشارة مكتوبة، وسيصلك الرد المفصل من المحامي عبر بريدك الإلكتروني خلال 24 إلى 48 ساعة كحد أقصى.</Text></View>; }
export function BookingAvailability({ selectedDate, selectedTime, days, slots, onDate, onTime, duration=60 }: { selectedDate:string; selectedTime:string; days:{date:string;dayNum:number;monthLabel:string;weekdayLabel:string}[]; slots:{time:string;available:boolean}[]; onDate:(d:string)=>void; onTime:(t:string)=>void; duration?:number }) {
 return <View style={styles.section}><Text style={styles.title}>مواعيدي</Text><Text style={styles.caption}>اختر الموعد المناسب لك قبل المتابعة</Text><View style={styles.days}>{days.map(d=><TouchableOpacity key={d.date} onPress={()=>onDate(d.date)} style={[styles.day,selectedDate===d.date&&styles.dayActive]}><Text style={[styles.small,selectedDate===d.date&&styles.activeText]}>{d.monthLabel}</Text><Text style={[styles.num,selectedDate===d.date&&styles.activeText]}>{d.dayNum}</Text><Text style={[styles.small,selectedDate===d.date&&styles.activeText]}>{d.weekdayLabel}</Text></TouchableOpacity>)}</View>{selectedDate&&<View style={styles.slots}>{slots.map(s=><TouchableOpacity key={s.time} disabled={!s.available} onPress={()=>s.available&&onTime(s.time)} style={[styles.slot,!s.available&&styles.disabled,selectedTime===s.time&&styles.slotActive]}><Text style={[styles.slotText,selectedTime===s.time&&styles.activeText]}>{s.time}</Text></TouchableOpacity>)}</View>}<Text style={styles.duration}>مدة الموعد: {duration} دقيقة</Text></View>;
}
const styles=StyleSheet.create({section:{backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:16,padding:15,marginBottom:12},title:{fontSize:15,fontFamily:"Inter_700Bold",color:C.foreground,textAlign:"right"},caption:{fontSize:10,color:C.mutedForeground,textAlign:"right",marginTop:4},grid:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:11},typeCard:{width:"48%",minHeight:82,borderWidth:1,borderColor:C.border,borderRadius:13,padding:10,alignItems:"center",justifyContent:"center",gap:7},icon:{width:34,height:34,borderRadius:10,alignItems:"center",justifyContent:"center"},label:{fontSize:10,fontFamily:"Inter_600SemiBold",color:C.foreground,textAlign:"center"},notice:{flexDirection:"row",alignItems:"center",gap:10,backgroundColor:"#FFF9E8",borderWidth:1,borderColor:"#E7C96B",borderRadius:14,padding:13,marginBottom:12},noticeText:{flex:1,fontSize:11,lineHeight:18,color:C.foreground,textAlign:"right",fontFamily:"Inter_500Medium"},days:{flexDirection:"row",gap:8,marginTop:12},day:{minWidth:63,borderWidth:1,borderColor:C.border,borderRadius:12,padding:8,alignItems:"center"},dayActive:{backgroundColor:C.navy,borderColor:C.navy},small:{fontSize:9,color:C.mutedForeground},num:{fontSize:18,fontFamily:"Inter_700Bold",color:C.foreground,marginVertical:3},activeText:{color:"#fff"},slots:{flexDirection:"row",flexWrap:"wrap",gap:7,marginTop:12},slot:{paddingHorizontal:12,paddingVertical:9,borderWidth:1,borderColor:C.border,borderRadius:10},slotActive:{backgroundColor:C.gold,borderColor:C.gold},slotText:{fontSize:10,fontFamily:"Inter_600SemiBold",color:C.foreground},disabled:{opacity:.35},duration:{fontSize:9,color:C.mutedForeground,textAlign:"right",marginTop:10}});
