import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminRouter from "./admin";
import bookingsRouter from "./bookings";
import availabilityRouter from "./availability";
import authRouter from "./auth";
import profileRouter from "./profile";
import reviewsRouter from "./reviews";
import notificationsRouter from "./notifications";
import documentHandoversRouter from "./documentHandovers";
import paymentProofsRouter from "./paymentProofs";
import consultationDocumentationRouter from "./consultationDocumentation";
import representationQuoteRequestsRouter from "./representationQuoteRequests";
import lawyerProposalsRouter from "./lawyerProposals";
import agreementsRouter from "./agreements";
import legalRepresentationDocumentsRouter from "./legalRepresentationDocuments";
import casesRouter from "./cases";
import caseHearingsRouter from "./caseHearings";
import fundMilestoneRouter from "./fundMilestone";
import allocateMilestoneRouter from "./allocateMilestone";
import createMilestoneProofRouter from "./createMilestoneProof";
import createMilestoneReleaseRequestRouter from "./createMilestoneReleaseRequest";
import disputeMilestoneReleaseRouter from "./disputeMilestoneRelease";
import releaseMilestoneRouter from "./releaseMilestone";
import refundMilestoneRouter from "./refundMilestone";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(adminRouter);
router.use(bookingsRouter);
router.use(availabilityRouter);
router.use(reviewsRouter);
router.use(notificationsRouter);
router.use(documentHandoversRouter);
router.use(paymentProofsRouter);
router.use(consultationDocumentationRouter);
router.use(representationQuoteRequestsRouter);
router.use(lawyerProposalsRouter);
router.use(agreementsRouter);
router.use(legalRepresentationDocumentsRouter);
router.use(casesRouter);
router.use(caseHearingsRouter);
router.use(fundMilestoneRouter);
router.use(allocateMilestoneRouter);
router.use(createMilestoneProofRouter);
router.use(createMilestoneReleaseRequestRouter);
router.use(disputeMilestoneReleaseRouter);
router.use(releaseMilestoneRouter);
router.use(refundMilestoneRouter);

export default router;
