import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React from "react";
import { Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import colors from "@/constants/colors";
const C=colors.light;
const ITEMS=[{icon:"file-text",title:"عرض سعر توكيل جديد",text:"لديك عرض أتعاب جديد من المحامي — قريبًا",kind:"lawyer",time:"الآن"},{icon:"credit-card",title:"دفعة مرحلة مستحقة",text:"يرجى إيداع دفعة المرحلة لاستكمال الإجراءات القضائية",kind:"payment",time:"اليوم"},{icon:"shield",title:"مراجعة مستند",text:"تم إرسال إثبات إنجاز مرحلة للمراجعة خلال 72 ساعة",kind:"case",time:"اليوم"},{icon:"truck",title:"تحديث تسليم مستند",text:"الشحنة الدولية قيد المتابعة — قريبًا",kind:"delivery",time:"أمس"}];
export default function ClientNotifications(){const router=useRouter();const insets=useSafeAreaInsets();return <ScrollView style={styles.screen} contentContainerStyle={{paddingTop:insets.top+(Platform.OS==="web"?67:10),paddingBottom:insets.bottom+40}}><View style={styles.header}><TouchableOpacity onPress={()=>router.back()}><Feather name="arrow-right" size={22} color={C.foreground}/></TouchableOpacity><Text style={styles.title}>التنبيهات</Text><View style={{width:22}}/></View><View style={styles.banner}><Feather name="bell" size={18} color={C.gold}/><Text style={styles.bannerText}>تنبيهات مستشارك تساعدك على متابعة الاستشارات والعروض والقضايا خطوة بخطوة.</Text></View>{ITEMS.map((n,i)=><TouchableOpacity key={i} style={styles.item} activeOpacity={0.85}><View style={[styles.icon,{backgroundColor:n.kind==="payment"?"rgba(201,160,53,.12)":"#EEF2F8"}]}><Feather name={n.icon as any} size={18} color={n.kind==="payment"?C.gold:C.navy}/></View><View style={styles.copy}><View style={styles.row}><Text style={styles.itemTitle}>{n.title}</Text><Text style={styles.time}>{n.time}</Text></View><Text style={styles.text}>{n.text}</Text></View></TouchableOpacity>)}<View style={styles.future}><Feather name="clock" size={15} color={C.gold}/><Text style={styles.futureText}>الإرسال الفعلي والتنبيهات اللحظية وPush Notifications ستُربط في مرحلة الـBackend.</Text></View></ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:C.background,paddingHorizontal:20},header:{flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between",paddingVertical:16},title:{fontSize:20,fontFamily:"Inter_700Bold",color:C.foreground},banner:{flexDirection:"row-reverse",gap:9,alignItems:"flex-start",backgroundColor:C.navy,borderRadius:16,padding:14,marginBottom:16},bannerText:{flex:1,color:"#fff",fontSize:11,lineHeight:18,textAlign:"right"},item:{flexDirection:"row-reverse",alignItems:"center",gap:12,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:15,padding:14,marginBottom:10},icon:{width:40,height:40,borderRadius:12,alignItems:"center",justifyContent:"center"},copy:{flex:1},row:{flexDirection:"row-reverse",justifyContent:"space-between",gap:8},itemTitle:{flex:1,color:C.foreground,fontSize:13,fontFamily:"Inter_700Bold",textAlign:"right"},time:{color:C.mutedForeground,fontSize:10},text:{color:C.mutedForeground,fontSize:11,lineHeight:18,textAlign:"right",marginTop:4},future:{flexDirection:"row-reverse",gap:8,alignItems:"flex-start",backgroundColor:"rgba(201,160,53,.08)",borderRadius:14,padding:13,marginTop:4},futureText:{flex:1,color:C.mutedForeground,fontSize:11,lineHeight:18,textAlign:"right"}});
