const colors = {
  light: {
    text: "#0F172A",
    tint: "#0F6F6D",
    background: "#F8FAFA",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#0F6F6D",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F5F4",
    secondaryForeground: "#0F6F6D",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#C9A035",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#CBD5E1",
    input: "#CBD5E1",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    pending: "#F59E0B",
    gold: "#C9A035",
    turquoise: "#0F6F6D",
    turquoiseDark: "#0F6F6D",
    turquoiseLight: "#E8F5F4",
    navy: "#1B3A6B",
    navyLight: "#2D5499",
  },
  radius: 12,
};

export default colors;
