// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/CottagecoreFintechHomeScreen-RATKzU/App.tsx": () => import("../components/mockups/templates/CottagecoreFintechHomeScreen-RATKzU/App.tsx"),
  "./components/mockups/templates/CottagecoreFintechHomeScreen-ot7d9F/App.tsx": () => import("../components/mockups/templates/CottagecoreFintechHomeScreen-ot7d9F/App.tsx"),
  "./components/mockups/templates/CottagecoreFintechHomeScreen-u2mjxS/App.tsx": () => import("../components/mockups/templates/CottagecoreFintechHomeScreen-u2mjxS/App.tsx")
};
