import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React from "react";
import { Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import colors from "@/constants/colors";
const C = colors.light;
const steps=[['check-circle','الاتفاقية موقعة','تم تأكيد الاتفاقية من الطرفين'],['shield','الوكالة موثقة','بانتظار رفع/مراجعة المستند الرسمي'],['briefcase','قيد التنفيذ','تنفيذ مراحل التوكيل حسب نطاق العمل'],['flag','مكتملة','إغلاق القضية وتسوية الدفعات']];
export default function ActiveCasePreview(){const router=useRouter();const insets=useSafeAreaInsets();return <ScrollView style={styles.screen} contentContainerStyle={{paddingTop:insets.top+(Platform.OS==='web'?67:10),paddingBottom:insets.bottom+40}}><View style={styles.header}><TouchableOpacity onPress={()=>router.back()}><Feather name="arrow-right" size={21} color={C.foreground}/></TouchableOpacity><Text style={styles.title}>مساحة القضية النشطة</Text><View style={{width:21}}/></View><View style={styles.hero}><Text style={styles.kicker}>توكيل وتمثيل قانوني</Text><Text style={styles.heroTitle}>قضية تجريبية — عرض أتعاب</Text><Text style={styles.heroText}>واجهة المرحلة التالية بعد الدفع والتأكيد. جميع الإجراءات المالية والربط ستُفعل لاحقًا.</Text></View><Text style={styles.sectionTitle}>خط سير القضية</Text>{steps.map(([icon,title,text],i)=><View key={title} style={styles.stepRow}><View style={[styles.icon,{backgroundColor:i===0?'#ECFDF5':'rgba(201,160,53,.1)'}]}><Feather name={icon as any} size={16} color={i===0?C.success:C.gold}/></View><View style={{flex:1}}><Text style={styles.stepTitle}>{title}</Text><Text style={styles.stepText}>{text}</Text></View></View>)}<View style={styles.milestone}><View style={styles.milestoneHead}><Feather name="pie-chart" size={16} color={C.gold}/><Text style={styles.milestoneTitle}>مراحل الأتعاب</Text></View><View style={styles.bars}><View style={[styles.bar,styles.b30]}/><View style={[styles.bar,styles.b40]}/><View style={[styles.bar,styles.b30]}/></View><View style={styles.labels}><Text>30% البدء</Text><Text>40% الجلسات</Text><Text>30% الحكم والختام</Text></View></View><View style={styles.actions}><TouchableOpacity style={styles.disabled}><Feather name="file-text" size={15} color={C.mutedForeground}/><Text style={styles.disabledText}>رفع إثبات المرحلة · قريبًا</Text></TouchableOpacity><TouchableOpacity style={styles.disabled}><Feather name="send" size={15} color={C.mutedForeground}/><Text style={styles.disabledText}>طلب إفراج الدفعة · قريبًا</Text></TouchableOpacity></View></ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:C.background,paddingHorizontal:20},header:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center',paddingVertical:16},title:{fontSize:20,fontWeight:'800',color:C.foreground},hero:{backgroundColor:C.navy,borderRadius:19,padding:20,borderWidth:1,borderColor:'rgba(201,160,53,.3)'},kicker:{color:C.gold,fontSize:11,fontWeight:'800',textAlign:'right'},heroTitle:{color:'#fff',fontSize:18,fontWeight:'800',textAlign:'right',marginTop:4},heroText:{color:'rgba(255,255,255,.72)',fontSize:11,lineHeight:18,textAlign:'right',marginTop:6},sectionTitle:{fontSize:14,fontWeight:'800',color:C.foreground,textAlign:'right',marginVertical:15},stepRow:{flexDirection:'row-reverse',alignItems:'flex-start',gap:10,backgroundColor:C.card,borderRadius:14,borderWidth:1,borderColor:C.border,padding:13,marginBottom:9},icon:{width:35,height:35,borderRadius:11,alignItems:'center',justifyContent:'center'},stepTitle:{fontSize:12,fontWeight:'800',color:C.foreground,textAlign:'right'},stepText:{fontSize:10,lineHeight:17,color:C.mutedForeground,textAlign:'right',marginTop:2},milestone:{backgroundColor:C.card,borderRadius:15,borderWidth:1,borderColor:C.border,padding:14,marginTop:7},milestoneHead:{flexDirection:'row-reverse',gap:7,alignItems:'center'},milestoneTitle:{fontSize:13,fontWeight:'800',color:C.navy},bars:{flexDirection:'row-reverse',height:13,borderRadius:8,overflow:'hidden',marginTop:12},bar:{height:'100%'},b30:{flex:3,backgroundColor:'#C9A035'},b40:{flex:4,backgroundColor:'#1A2A4A'},labels:{flexDirection:'row-reverse',justifyContent:'space-between',marginTop:8,fontSize:10,color:C.mutedForeground},actions:{gap:9,marginTop:14},disabled:{flexDirection:'row-reverse',justifyContent:'center',alignItems:'center',gap:7,padding:13,borderRadius:12,borderWidth:1,borderColor:C.border,backgroundColor:C.card},disabledText:{fontSize:11,fontWeight:'700',color:C.mutedForeground}});
