import { Feather } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React, { useState } from "react";
import { Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import colors from "@/constants/colors";
const C=colors.light;
const OPTIONS=[{key:"local-agent",title:"إرسال مندوب من قبل المكتب",desc:"يطلب العميل استلامًا محليًا ويؤكد التسليم عبر OTP من 4 أرقام.",icon:"user-check"},{key:"office",title:"تسليم مباشر في مقر المكتب",desc:"عرض عنوان المكتب وساعات العمل وموقع الخريطة وإصدار إيصال إلكتروني.",icon:"map-pin"},{key:"international",title:"الشحن الدولي الموثق",desc:"يظهر تلقائيًا عند اختلاف بلد العميل عن بلد مكتب المحامي.",icon:"globe"}];
export default function DocumentHandover(){const router=useRouter();const insets=useSafeAreaInsets();const {id}=useLocalSearchParams();const [selected,setSelected]=useState("office");return <ScrollView style={styles.screen} contentContainerStyle={{paddingTop:insets.top+(Platform.OS==="web"?67:10),paddingBottom:insets.bottom+40}}><View style={styles.header}><TouchableOpacity onPress={()=>router.back()}><Feather name="arrow-right" size={22} color={C.foreground}/></TouchableOpacity><Text style={styles.title}>تسليم المستندات</Text><View style={{width:22}}/></View><View style={styles.case}><Feather name="folder" size={18} color={C.gold}/><Text style={styles.caseText}>القضية {String(id??"CASE-001")}</Text></View><Text style={styles.intro}>سيحدد النظام لاحقًا الخيارات المناسبة تلقائيًا حسب بلد ومدينة العميل ومكتب المحامي.</Text>{OPTIONS.map(o=>{const active=selected===o.key;return <TouchableOpacity key={o.key} style={[styles.card,active&&styles.active]} onPress={()=>setSelected(o.key)}><View style={[styles.icon,active&&styles.iconActive]}><Feather name={o.icon as any} size={20} color={active?C.gold:C.mutedForeground}/></View><View style={styles.copy}><Text style={styles.cardTitle}>{o.title}</Text><Text style={styles.cardDesc}>{o.desc}</Text></View><View style={[styles.radio,active&&styles.radioActive]}>{active&&<View style={styles.dot}/>}</View></TouchableOpacity>})}<View style={styles.guidance}><Feather name="alert-triangle" size={16} color={C.gold}/><Text style={styles.guidanceText}>للشحن الدولي: قد تتطلب الوكالة تصديق وزارة الخارجية وسفارة بلد القضية وفق المتطلبات القانونية المعمول بها.</Text></View><View style={styles.tracking}><Feather name="truck" size={17} color={C.navy}/><View style={{flex:1}}><Text style={styles.trackTitle}>التتبع والإيصال الرقمي</Text><Text style={styles.trackText}>Dispatched → In Transit → Customs Cleared → Delivered</Text></View></View><TouchableOpacity style={styles.primary} onPress={()=>router.back()}><Text style={styles.primaryText}>متابعة — قريبًا</Text><Feather name="arrow-left" size={16} color="#fff"/></TouchableOpacity></ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:C.background,paddingHorizontal:20},header:{flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between",paddingVertical:16},title:{fontSize:20,fontFamily:"Inter_700Bold",color:C.foreground},case:{flexDirection:"row-reverse",alignItems:"center",gap:8,backgroundColor:C.navy,borderRadius:14,padding:13,marginBottom:12},caseText:{color:"#fff",fontSize:12,fontFamily:"Inter_600SemiBold"},intro:{color:C.mutedForeground,fontSize:11,lineHeight:18,textAlign:"right",marginBottom:16},card:{flexDirection:"row-reverse",alignItems:"center",gap:11,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:16,padding:14,marginBottom:10},active:{borderColor:"rgba(201,160,53,.55)"},icon:{width:44,height:44,borderRadius:13,backgroundColor:"#F3F4F6",alignItems:"center",justifyContent:"center"},iconActive:{backgroundColor:"rgba(201,160,53,.12)"},copy:{flex:1},cardTitle:{fontSize:13,fontFamily:"Inter_700Bold",color:C.foreground,textAlign:"right"},cardDesc:{fontSize:10.5,color:C.mutedForeground,lineHeight:17,textAlign:"right",marginTop:3},radio:{width:20,height:20,borderRadius:10,borderWidth:1.5,borderColor:C.border,alignItems:"center",justifyContent:"center"},radioActive:{borderColor:C.gold},dot:{width:10,height:10,borderRadius:5,backgroundColor:C.gold},guidance:{flexDirection:"row-reverse",gap:8,alignItems:"flex-start",backgroundColor:"rgba(201,160,53,.08)",borderWidth:1,borderColor:"rgba(201,160,53,.2)",borderRadius:14,padding:13,marginTop:6},guidanceText:{flex:1,color:C.mutedForeground,fontSize:10.5,lineHeight:18,textAlign:"right"},tracking:{flexDirection:"row-reverse",gap:10,alignItems:"center",backgroundColor:"#EEF2F8",borderRadius:14,padding:13,marginTop:12},trackTitle:{fontSize:12,fontFamily:"Inter_700Bold",color:C.navy,textAlign:"right"},trackText:{fontSize:9.5,color:C.mutedForeground,marginTop:3,textAlign:"right"},primary:{flexDirection:"row-reverse",justifyContent:"center",alignItems:"center",gap:8,backgroundColor:C.navy,borderRadius:14,paddingVertical:16,marginTop:18},primaryText:{color:"#fff",fontSize:14,fontFamily:"Inter_700Bold"}});
